import type { Metadata } from "next";
import "./globals.css";
import { inter } from "@/font";
import AsideBar from "@/components/asideBar/AsideBar";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <div style={{ display: "flex" }}>
          <AsideBar />
          <div style={{ marginLeft: "250px" }}>
            <Header routes="/" />
            <div style={{ marginTop: "50px" }}>{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
