import type { Metadata } from "next";
import "./globals.css";
import { inter } from "@/font";
import AsideBar from "@/components/asideBar/AsideBar";
import Header from "@/components/Header";
import WritePostInput from "@/components/home/WritePostInput";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <div
          style={{
            display: "flex",
            width: "1200px",
            margin: "0 auto",
            borderRight: "1px solid #bdbdbd",
            minHeight:"100vh"
          }}
        >
          <AsideBar />
          <div style={{ marginLeft: "150px", width: "100%" }}>
            <Header routes="/" />
            <WritePostInput />
            <div
              style={{
                marginTop: "190px",
              }}
            >
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
