"use client";

import type { Metadata } from "next";
import AsideBar from "@/components/asideBar/AsideBar";
import Header from "@/components/Header";
import WritePostInput from "@/components/home/WritePostInput";
import { useEffect, useState } from "react";
import { usePathname } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  const pathValue = usePathname();

  const [tabValue, setTabValue] = useState("");

  useEffect(() => {
    const getPathValue = () => {
      if (pathValue === "/") {
        setTabValue("Home");
      }

      if (pathValue === "/friends") {
        setTabValue("Frineds");
      }

      if (pathValue === "/commercial") {
        setTabValue("Commercial");
      }

      if (pathValue === "/profile") {
        setTabValue("Profile");
      }

      if (pathValue === "/messages") {
        setTabValue("Messages");
      }
    };

    getPathValue();
  }, [pathValue]);

  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <div
          style={{
            display: "flex",
            width: "100%",
            borderRight: "1px solid #bdbdbd",
            minHeight: "100vh",
          }}
        >
          <AsideBar />
          <div style={{ paddingLeft: "13%", width: "100%" }}>
            <Header routes={tabValue} />
            <WritePostInput />
            <div
              style={{
                width: "100%",
                marginTop: "150px",
              }}
            >
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
