"use client";

import type { Metadata } from "next";
import AsideBar from "@/components/asideBar/AsideBar";
import Header from "@/components/Header";
import WritePostInput from "@/components/home/WritePostInput";
import { useEffect, useState } from "react";
import { usePathname } from "next/navigation";
import styles from "./style/layout.module.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  const pathValue = usePathname();

  const [tabValue, setTabValue] = useState("");

  useEffect(() => {
    const getPathValue = () => {
      if (pathValue === "/") {
        setTabValue("Home");
      }

      if (pathValue === "/friends") {
        setTabValue("Frineds");
      }

      if (pathValue === "/commercial") {
        setTabValue("Commercial");
      }

      if (pathValue === "/profile") {
        setTabValue("Profile");
      }

      if (pathValue === "/messages") {
        setTabValue("Messages");
      }
    };

    getPathValue();
  }, [pathValue]);

  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <div className={styles.Layout_Container}>
          <AsideBar />
          <div className={styles.Layout_Wrapper}>
            <Header routes={tabValue} />
            <WritePostInput />
            <div className={styles.Contents_Container}>{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
